version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  backlogger:
    build: ./backlogger
    ports:
      - 8080:4000
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=backlogger
      - PGHOST=db
      - PGPORT=5432
      - DATABASE_URL=ecto://postgres:postgres@db/backlogger
      - SECRET_KEY_BASE=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

volumes:
  db:
    driver: local
